### ISSUE TITLE
Docs refer to a non-existent "ClipperProvider"

### ISSUE THREAD

**Issue by JDougherty** [aureplop/django-allauth-cas#1]
In Step 2 of Basic Setup, "[Create the provider](https://django-allauth-cas.readthedocs.io/en/latest/basic_setup.html#create-the-provider)", the code references `ClipperProvider` which is not explained and I cannot find in this codebase. Was that meant to be MyCASProvider?

**Comment by aureplop** [comment]
You are right. It is a vestige of my original use case.
Thank you for raising this issue :-)
